name: "Update hellgrenmick.se"
on:
    push:
        branches:
            - master

jobs:
    deploy:
        name: "Update hellgrenmick.se"
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2

            - name: "rsync"
              run: sshpass -p "${{ secrets.SSHPassword }}" \
                  rsync --recursive \
                  --files-from=./syncfiles \
                  . 134609_jm@ssh.binero.se:/storage/content/09/134609/hellgrenmick.se/public_html
